import React, { useState, useEffect } from 'react';
import API from '../../services/authService';
import '../../components/Layout.css';

const REPORT_TYPES = [
  { key: 'proposals',  icon: '📄', label: 'Proposals Report',
    desc: 'All research proposals with researcher, type, and status.' },
  { key: 'grants',     icon: '🎓', label: 'Grants Report',
    desc: 'All grant and incentive applications with statuses.' },
  { key: 'repository', icon: '🗄', label: 'Repository Report',
    desc: 'All archived research outputs in the repository.' },
  { key: 'activity',   icon: '📊', label: 'Activity Report',
    desc: 'System-wide summary — users, proposals, grants, and archives.' },
];

const ReportsPage = () => {
  const [history,     setHistory]     = useState([]);
  const [downloading, setDownloading] = useState(null);
  const [alert,       setAlert]       = useState(null);

  const fetchHistory = async () => {
    try {
      const res = await API.get('/reports');
      setHistory(res.data.reports || []);
    } catch { setHistory([]); }
  };

  useEffect(() => { fetchHistory(); }, []);

  const downloadReport = async (type) => {
    setDownloading(type);
    setAlert(null);
    try {
      const res = await API.get(`/reports/${type}`, { responseType: 'blob' });
      const url  = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `ayon-${type}-report.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
      setAlert({ type: 'success', msg: 'Report downloaded successfully!' });
      fetchHistory();
    } catch {
      setAlert({ type: 'error', msg: 'Failed to generate report.' });
    } finally {
      setDownloading(null);
    }
  };

  return (
    <>
      <div className="page-header">
        <h1>Reports</h1>
        <p>Generate and download PDF reports of system activity.</p>
      </div>

      {alert && <div className={`alert alert-${alert.type}`}>{alert.msg}</div>}

      {/* Report cards */}
      <div style={{ display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: 16, marginBottom: 24 }}>
        {REPORT_TYPES.map(r => (
          <div key={r.key} className="panel" style={{ marginBottom: 0 }}>
            <div className="panel-body" style={{ display: 'flex',
              flexDirection: 'column', gap: 10 }}>
              <div style={{ fontSize: '1.8rem' }}>{r.icon}</div>
              <p style={{ fontWeight: 700, color: '#1a3a5c',
                margin: 0, fontSize: '0.95rem' }}>{r.label}</p>
              <p style={{ color: '#718096', margin: 0,
                fontSize: '0.82rem', lineHeight: 1.5, flex: 1 }}>{r.desc}</p>
              <button className="btn btn-primary btn-sm"
                disabled={downloading === r.key}
                onClick={() => downloadReport(r.key)}>
                {downloading === r.key ? 'Generating...' : '⬇ Download PDF'}
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Report history */}
      <div className="panel">
        <div className="panel-header"><h2>Recently Generated Reports</h2></div>
        <table className="data-table">
          <thead>
            <tr><th>Report</th><th>Type</th><th>Generated By</th><th>Date</th></tr>
          </thead>
          <tbody>
            {history.map(r => (
              <tr key={r.report_id}>
                <td><strong>{r.report_title}</strong></td>
                <td>
                  <span className="badge badge-blue">{r.report_type}</span>
                </td>
                <td>{r.users ? `${r.users.first_name} ${r.users.last_name}` : '—'}</td>
                <td style={{ color: '#718096' }}>
                  {r.generated_at ? new Date(r.generated_at).toLocaleString() : '—'}
                </td>
              </tr>
            ))}
            {history.length === 0 && (
              <tr><td colSpan={4}>
                <div className="empty-state"><p>No reports generated yet.</p></div>
              </td></tr>
            )}
          </tbody>
        </table>
      </div>
    </>
  );
};

export default ReportsPage;